services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: horizon-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=event-horizon-db
      - DB_PORT=5432
      - SERVER_IP=89.169.137.16
      - SERVER_SCHEMA=http
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minio_user
      - MINIO_SECRET_KEY=minio_qwerty
    depends_on:
      - postgres
      - minio
    networks:
      - event-horizon

  postgres:
    image: postgres:latest
    container_name: event-horizon-db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: event_horizon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - event-horizon

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_qwerty
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SITE_REGION: eu-west-1
    volumes:
      - minio_data:/data
    networks:
      - event-horizon

volumes:
  postgres_data:
  minio_data:

networks:
  event-horizon:
    driver: bridge
